### ISSUE TITLE
Jobs was enqueued but not performed

### ISSUE THREAD

**Issue by MMacku** [que-rb/que#227]
Hello, first of I'm sorry for lack of information but i haven't more.

We use Que with Rails and yesterday occur weird thing. In production.log we have:
```
Enqueued SendBranchSmsJob (Job ID: c41f5eb0-0ce6-407e-8682-2ad6c9dfe18e) to Que(default) with arguments: 13374
Enqueued SendCustomerSmsJob (Job ID: a43c5622-d2df-461b-a158-0837727b0cfa) to Que(default) with arguments: 13374
...
Performing SendCustomerSmsJob (Job ID: a43c5622-d2df-461b-a158-0837727b0cfa) from Que(default) with arguments: 13374
...
```
But `SendBranchSmsJob` never performed or failure. Also we cant found it in Que db table.

We call this jobs from other jobs, but second one (SendCustomerSmsJob) was performed correct.

Rails: 5.2.0
Que: 0.14.3
pg: 0.21.0

Postgre: 9.6.0
Centos: centos-release-7-5.1804.el7.centos.2.x86_64

**Comment by chanks** [comment]
Yeah, sorry, but that's not a lot of information to go on. Does SendBranchSmsJob ever perform, or does it always just disappear? Do you know if the SMS actually went through, or are you just using the logs to figure out what happened?

**Comment by techiedog** [comment]
@MMacku Did you ever work out the problem here?

We have come across a very similar issue with an email send job. Some times the email is sent, sometime it isn't  - no errors!
We see the job Enqueued in the log but nothing happens. Other times it works fine!

**Comment by techiedog** [comment]
@MMacku No problem, thanks for the reply. 

We couldn't find the problem or a direct solution. In the end we coded a custom job instead.

**Comment by oeoeaio** [comment]
Closing this for now. Happy for anyone to re-open if they have any more information or (even better) are able to reliably reproduce the issue.
