### ISSUE TITLE
Rails' GlobalId support seems to be broken

### ISSUE THREAD

**Issue by chanks** [que-rb/que#236]
See spec failures at https://circleci.com/gh/chanks/que/1717 (among others). It's possible that things are working fine and the specs just need to be updated, though, I haven't paid attention to developments in Rails-land in a while.

**Comment by siegy22** [comment]
When integrating into a rails app, everything GID related is passed properly into the job when it's executed with the following setup:

Rails: 6.0.0.rc1
Ruby: 2.6.2
que: 1.0.0.beta3
postgres: 9.6.11

**Comment by siegy22** [comment]
I'm going to check if anything is broken of the GlobalID support. As of right now, it seems everything's working fine.

**Comment by morgoth** [comment]
we're using que 1.0.beta4 as AJ adapter and passing AR objects into job params that are serialized into GID and it's working fine for us

**Comment by siegy22** [comment]
I'm closing this for now 👍 @morgoth thanks for your feedback.
