### ISSUE TITLE
1.0.0 Release?

### ISSUE THREAD

**Issue by siegy22** [que-rb/que#245]
I was asking myself why the last release (`1.0.0.beta3` as of today) is over a year old 😄 

Did que come to an end before it reached its stable version?
I've also found other issues from Sep. 2017 asking the same thing.

So what does que need to have before being 1.0?

**Comment by ivan-kolmychek** [comment]
I think [this discussion](https://groups.google.com/forum/#!topic/que-talk/GwPIO2e8Ihg) may be relevant.

**Comment by chanks** [comment]
Yeah, I have a new day job where I don’t/can’t use Que, and I don’t even
use Ruby that much in my spare time anymore, so it hasn’t been a priority
to me. I’d be open to a new maintainer for it, if anyone is interested.

**Comment by coffenbacher** [comment]
Que is such an effective project and mostly 'complete' as far as these things go, it'd be a shame to see it stuck in `1.0.beta` forever.

I don't have any experience in public gem release management, so I don't feel comfortable touching that part for the first time as a major version bump, but if @chanks or anyone else wants to do it I'll buy them a coffee 😆 I know some related projects like que-scheduler have been waiting on it.

Beyond the 1.0 release, adding someone as a maintainer even if it's just in the most basic 'merge decent PRs' capacity would be great, better a very-lightly-maintained project than a dead one. I'd do it if no one else, but I'd nominate any PR author (@mikehale, @siegy22, @giovannibonetti) if any of them want to. All made good contributions recently.

**Comment by 6temes** [comment]
Funny thing, even Heroku have a branch of this repository. It would be great if this project is not abandoned.

https://github.com/heroku/que

**Comment by mikehale** [comment]
I'm a big fan of que, but not sure how much time I could realistically dedicate to the project. Also I've never run a public repo before so I'm not quite sure what to expect and what is expected.

**Comment by siegy22** [comment]
I would offer my help in coordinating and preparing the releases and also review some PRs, but I don't really have time to actually develop on que itself 😐.

**Comment by ioquatix** [comment]
Wondering if this will see a 1.0 release too.

**Comment by sandstrom** [comment]
@chanks How about simply releasing a 1.0 (it seems stable enough), and then update the readme to something like this:

```
Que is a stable, active job queue that is used in multiple production environments. However, the original maintainer finds less time to work on it these days, so would be open to assigning one or two new maintainers.
```

**Comment by chanks** [comment]
I'm not wild about releasing 1.0 when I don't have the time to put in to respond to issues. Especially since I believe the Rails integration has fallen out of date yet again.

**Comment by nearapogee** [comment]
Late to the party.... @chanks I see where you are coming from and feel the pain of maintaining something you don't use often.

I would be interested in helping to maintain, though I haven't looked at what is on the docket to get to 1.0.0 and the latest Rails ActiveJob implementation. I can't look right now, but happy to dialog on this.

I read the source quite often when I have questions, so I don't think this would be too difficult.

**Comment by siegy22** [comment]
@chanks To push this, I'm available to take this over and push it to a 1.0 release.
Together with @nearapogee and others maybe?

**Comment by chanks** [comment]
Sure, want to fork it to a repo/organization where it can be more of a shared effort? Something like `que/que`?

I also own `que-rb.com`, which I've never done anything with, and which is expiring in a couple weeks. I'm happy to transfer it to you if you like.

**Comment by siegy22** [comment]
I created the organization `que-rb` and will fork `que` in there.

I also invited you as a member.

**Comment by nearapogee** [comment]
I would be happy to help! We use que a lot. @siegy22 If you can help narrow down what we need to do, to get to 1.0 that would be incredibly helpful! Let me know what I can do.

**Comment by chanks** [comment]
Alright, cool. I'm happy to transfer rubygems.org push permissions over, but I've never done that before, so let me know what I can do about it.

Also if anyone wants `que-rb.com` let me know before October 4th, that's when it expires.

**Comment by nearapogee** [comment]
@chanks I'd be happy to take over `que-rb.com`. Feel free to email me about the details.

**Comment by siegy22** [comment]
I created a discord server for the community to have a chat.
Everyone's welcome: https://discord.gg/B3EW32H

I feel like the google group is kind of dead, I'm also gonna change the link in the README.

@chanks Can you add me to the maintainers/owners on https://rubygems.org/gems/que so I would be able to release a new version if needed?

**Comment by aried3r** [comment]
Hey! Awesome to see this project being picked up. I was just wondering, could this repo be transferred to the new organization instead of being forked? Would mean keeping the issues, PRs and also people would be redirected to it, when visiting this repo using the old URL.

WDYT?

**Comment by siegy22** [comment]
It really depends on @chanks, IMO it doesn't really matter. The fork indicates that the author is still @chanks, and I would like to give him credit for that.

**Comment by chanks** [comment]
@siegy22 Tried this at the command line:

```
gem owner que -a yves@siegrist.io
Adding yves@siegrist.io: Owner could not be found.
```

Is there a different email address you use for rubygems.org? Or there may be a CLI arg I'm missing.

**Comment by aried3r** [comment]
I agree about the credit part. But his commits will stay, he'll remain author in the `.gemspec` file and we can even leave a nice note in the README. :)

But technically speaking, using a fork has some downsides. For example (if the documentation is still up to date), forks [cannot be searched](https://help.github.com/en/articles/searching-in-forks).

And there's some minor downsides, like discoverability. Google results will probably point to the original repo. The original should probably be archived and put into read-only mode. So people will have to scroll down to the README, read a note about a fork, go there, ask their question there etc.
Also issues are "distributed" if not re-opened in the fork.

Although this is is of course a "what if?" scenario.

That being said, if @chanks want to leave this repo untouched, I completely understand, and I as mentioned in the beginning, I absolutely believe in credit where credit is due!

@chanks, what do you think?

**Comment by chanks** [comment]
I'm fine with transferring the repo, I assume the fork would have to be deleted first?

**Comment by siegy22** [comment]
@chanks Yeah I did use a different email address, but I changed it now to `yves@siegrist.io`, just try again 😄

**Comment by siegy22** [comment]
@chanks I deleted the fork, you can now transfer the repo 😄

**Comment by chanks** [comment]
Alright, added @siegy22 as an owner, but transferring the repo failed with `You don’t have the permission to create public repositories on que-rb`

**Comment by siegy22** [comment]
Did you accept the invitation of the organization?

**Comment by chanks** [comment]
Ah, there we go, I guess I didn't receive the last invitation for some reason.

**Comment by chanks** [comment]
Alright, moved.

**Comment by siegy22** [comment]
Ok I think we're ready to close this issue now, thank you guys. 

I'll try to make a roadmap for 1.0!
