### ISSUE TITLE
Completely flush Que (0.14.3)

### ISSUE THREAD

**Issue by Tinusw** [que-rb/que#258]
Basically I've got a situation where I need to:

- Stop all current Jobs.
- Clear the current Que.
- Clear all historically run jobs, so every single job can be re-executed from scratch.

My problem is that I am running Que in async mode in the same thread as puma, making it impossible for me to kill Que completely.

Is there anyway I can do this in the console?

```
Que::Worker.workers.each(&:stop)
Que.clear!
QueJob.count
# I expect QueJob.count to return 0
# Some way to flush que historic jobs completely?

```

Any help would be greatly appreciated

Tinus

**Comment by kofronpi** [comment]
@Tinusw  `QueJob.delete_all` ?

**Comment by siegy22** [comment]
If you're running queue inside a puma thread or worker, you would have to shutdown the main thread of puma to completly shut it down. And have you tried the statement from @kofronpi?

**Comment by Tinusw** [comment]
Thank you all for the info!

@kofronpi saved the day.
