### ISSUE TITLE
What are que_values?

### ISSUE THREAD

**Issue by sheerun** [que-rb/que#265]
I've noticed that que_values is created in database but is not used anywhere in code. What is going on?

**Comment by sheerun** [comment]
Also Locker class which is the only thing that uses que_lockes is not ssed anywhere in code except in tests. Also, what is going on? :)

**Comment by siegy22** [comment]
The original author added the following comment above the `que_values` table creation:

```
-- This is somewhat heretical, but we're going to need some more flexible
-- storage to support various features without requiring a ton of migrations,
-- which would be a lot of hassle for users. Hopefully this will be used smartly
-- and sparingly (famous last words).
```
