### ISSUE TITLE
readme link "how to write a reliable job" returns 404

### ISSUE THREAD

**Issue by Roko131** [que-rb/que#268]
Hi.

At readme:
Que does everything it can to ensure that jobs you queue are performed exactly once (though the occasional repetition of a job can be impossible to avoid - see the docs on [how to write a reliable job](https://github.com/que-rb/que/blob/master/docs/writing_reliable_jobs.md)).

The **how to write a reliable job** returns 404.
https://github.com/que-rb/que/blob/master/docs/writing_reliable_jobs.md

![image](https://user-images.githubusercontent.com/3532929/72445938-45f02700-37bb-11ea-8e80-deea7d44c313.png)

**Comment by MyklClason** [comment]
This is actually a general issue with the file. It was multiple documents, but those documents have been combined into one. However, the internal links within the document don't seem to have been updated.

Added a PR for it.

**Comment by Roko131** [comment]
Still getting 404.
From here:
https://github.com/que-rb/que
When clicking 
(though the occasional repetition of a job can be impossible to avoid - see the docs on [how to write a reliable job](https://github.com/que-rb/que/blob/master/docs/writing_reliable_jobs.md))

**Comment by MyklClason** [comment]
Unclear what happened, looks like it was merged, but but no change to
master. Odd.

**Comment by siegy22** [comment]
The problem is: There are two `README.md`s, one in the root and one in the `docs/` directory.
The PR #269 only fixed the one in `docs/` and not the "main" one.

This has been fixed in https://github.com/que-rb/que/commit/52593031a7eef2d52ac38eceb2d8df776ec74090
