### ISSUE TITLE
How can I "force kill" or "cancel" Running Jobs?

### ISSUE THREAD

**Issue by 1c7** [que-rb/que#286]
## Why
1.  I wrote a job that calculate statistics  (ActiveRecord.count)
2. the job work fine on my local dev machine (macbook pro) (job get done **under 1 minutes**)
3. "staging" enviroment have quite a lot data, the  job run for **more than 1 hours**

So clearly I need optimize my code, so I don't need these running jobs anymore.

## Question
How can I just "force kill" or "cancel" these running jobs?

Thank you

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/81135676-c36abd80-8f8b-11ea-84ad-3b137e8cd3f0.png)

![image](https://user-images.githubusercontent.com/1804755/81135688-cebde900-8f8b-11ea-86d1-987c646b508a.png)

**Comment by 1c7** [comment]
## One more question: Can I set Timeout? 
If a job run more than 5 minutes, just kill it

**Comment by 1c7** [comment]
## More info:
1. I deploy my application on AWS ECS, (this ECS thingy work just like Docker Swarm or K8S)
2. I could "force deploy" to restart "que worker" service in my cluster
3. it work, it did restart
4. but because que got "Safety" feature, the running jobs didn't get kill, it just get pick up and keep running (which in this case is not what I want)

**Comment by 1c7** [comment]
## Seem like delete all the records in "que_jobs" table works?

![image](https://user-images.githubusercontent.com/1804755/81136063-07aa8d80-8f8d-11ea-8eea-556ad83cd9c6.png)  

![image](https://user-images.githubusercontent.com/1804755/81136072-0d07d800-8f8d-11ea-8d07-f563a4549014.png)

**Comment by siegy22** [comment]
You can force kill the que process with `kill -9`, this will stop any running jobs.
