### ISSUE TITLE
No such file or directory at up.sql

### ISSUE THREAD

**Issue by duartemvix** [que-rb/que#300]
I'm getting StandardError: An error has occurred, this and all later migrations canceled:

No such file or directory @ rb_sysopen - /home/mat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/que-0.14.3/lib/que/migrations/4/up.sql
/home/mat/app/fornido/db/migrate/20201215063204_create_que_schema.rb:6:in `up'

I received this upon trying to run migrations right after writing them in db/

**Comment by nbarthel** [comment]
I had this issue initially also.  You need to switch to sql format and delete schema.rb.  Should resolve the problem.

**Comment by duartemvix** [comment]
> I had this issue initially also. You need to switch to sql format and delete schema.rb. Should resolve the problem.

I'll look into it. Thanks for reaching out so quickly.

**Comment by duartemvix** [comment]
> I had this issue initially also. You need to switch to sql format and delete schema.rb. Should resolve the problem.

Can you elaborate on switching to sql format? All I've seen is the source code for 4.sql which is raw SQL but I'm not sure how that would be put in migrations. I've send Que.migrate! to run with Rails' execute as you would do with SQL but no success.

**Comment by duartemvix** [comment]
> > I had this issue initially also. You need to switch to sql format and delete schema.rb. Should resolve the problem.
> 
> Can you elaborate on switching to sql format? All I've seen is the source code for 4.sql which is raw SQL but I'm not sure how that would be put in migrations. I've seen Que.migrate! to run with Rails' execute as you would do with SQL but no success.

**Comment by duartemvix** [comment]
Ops, I just made the mistake of following the Que 1.0 guides and README instructions while I'm on Que 0.14

**Comment by duartemvix** [comment]
Solved. Thanks!
