### ISSUE TITLE
How to avoid scheduling duplicate jobs?

### ISSUE THREAD

**Issue by dtbaker** [que-rb/que#308]
Hello, is it possible to avoid scheduling duplicate jobs? 

Use case: We have a UI where administrative actions can kick off a job. There could be 10 or so admin actions performed on an "item" within a minute, and we'd like to only have 1 job kicked off for those. 

It would be great if I could do something like:

```
self.run_at = proc { 1.hour.from_now }
self.avoid_duplicates = true
```

so I could enqueue this job multiple times within the hour and it would only result in a single job running. 

While trying to do this myself all I could find was `Que.job_stats` which which gave me the class name, but not the arguments needed to look for duplicates myself.

```
irb(main):020:0> Que.job_stats.first
=> {:job_class=>"BuildDownloadAssetJob", :count=>1, :count_working=>0, :count_errored=>0, :highest_error_count=>0, :oldest_run_at=>2021-05-19 23:25:31.520674 +0000}
```

Any other ways we could do this? 

Thanks!

**Comment by ZimbiX** [comment]
Check out [que-locks](https://github.com/airhorns/que-locks) - as [noted](https://github.com/que-rb/que#related-projects) =)

**Comment by dtbaker** [comment]
Thanks, I think this one will still queue up `10` jobs one after the other, when I don't really want to add any jobs to the queue if one is already scheduled some time in the future.

**Comment by ZimbiX** [comment]
It's perhaps not described the best, but it actually does _two_ things: deduplication and serialisation. For our project, [we only needed the latter](https://github.com/airhorns/que-locks/issues/2).

**Comment by ZimbiX** [comment]
See this part of the source:

https://github.com/airhorns/que-locks/blob/3345df09d47eafe6fec30cffd51e6b33c1359392/lib/que/locks/job_extensions.rb#L17-L18

**Comment by dtbaker** [comment]
Perfect, that makes sense now if I read it correctly!

```
will prevent the enqueuing and execution of any other instance of the same job with the same arguments
```

Will give it a go now, cheers
