### ISSUE TITLE
Add que_jobs.created_at ?

### ISSUE THREAD

**Issue by joevandyk** [que-rb/que#33]
Not sure if it would be helpful to have a timestamp that indicates when the job was created. Possibly when it was last ran as well. 

I suppose you could figure that out from the retry count and the retry interval though..

Thoughts?

**Comment by ivawzh** [comment]
I want to regularly run a health check in question to see if workers are frozen. My plan is query count of jobs which are created more than 20 mins ago. If returned number is not 0, I would assume workers not healthy. Is there anyway you can achieve the same check with run_at but not missing the never ran jobs? Cheers.

**Comment by chanks** [comment]
You can add your own created_at column if you really want to (`ALTER TABLE
que_jobs ADD COLUMN created_at NOT NULL DEFAULT now()` should do it). I
don't see any reason it would interfere with normal operation.
