### ISSUE TITLE
Cannot migrate to V6 inside the ruby3 branch

### ISSUE THREAD

**Issue by daniel-prause** [que-rb/que#344]
Hi there! 

Que seems to be relying on the method `job_schema_version` during rails init. This makes migrations impossible.
You'll find the error down below:

```
rails generate migration MigrateQueToVersionSix
/Users/daniel/.rvm/gems/ruby-3.0.3/bundler/gems/que-12ff191a8f3a/lib/que/job.rb:25:in `<class:Job>': undefined method `job_schema_version' for Que:Module (NoMethodError)
```

We "fixed" this for us by monkey patching the Que module with a dummy job_schema_version method.

But fixing this within the ruby3 branch would be the right way, of course :-)

**Comment by ZimbiX** [comment]
Ah, right, yeah, I haven't rebased it on master yet to incorporate the necessary fix for `require 'que'`, https://github.com/que-rb/que/pull/343. I'll get to it soon; thanks for trying it out.

**Comment by ZimbiX** [comment]
Done
