### ISSUE TITLE
preload rails in rake tasks?

### ISSUE THREAD

**Issue by joevandyk** [que-rb/que#35]
With `rake que:work`, been running into undefined constants and other things that indicate that rails isn't fully loaded.

I noticed that resque here https://github.com/resque/resque/blob/1-x-stable/lib/resque/tasks.rb#L57 runs `Rails.application.eager_load!` on boot. 

que should do something similar, right?

**Comment by moveson** [comment]
`Rails.application.eager_load!` fixed similar problems in my rake task.
