### ISSUE TITLE
Flaky Errors 

### ISSUE THREAD

**Issue by fameoflight** [que-rb/que#359]
{"lib":"que","hostname":"railway","pid":14,"thread":25800,"event":"job_errored","job_id":16846,"elapsed":0.014063471,"error":"NoMethodError: undefined method `new' for nil:NilClass"} 

This does not happen when I run this locally. For context I am use safe_constantize in job. 

And even more concerning is no error is begin raised Bugsnag (my exception tracking system). Any idea's what might be going on here. Here is relevant Gemfile.lock 

    que (1.4.0)
    que-scheduler (4.3.0)
      activesupport (>= 5.0)
      fugit (~> 1.1, >= 1.1.8)
      hashie (>= 3, < 6)
      que (>= 0.14, <= 2.0.0)

**Comment by ZimbiX** [comment]
Check the que_jobs table for the backtrace, and make sure you've set up an error handler to send them to Bugsnag

**Comment by ZimbiX** [comment]
We can't help without more details, so I'm going to assume this was an app-specific bug and close the issue. Feel free to re-open otherwise.
