### ISSUE TITLE
Proper way of removing Que from project?

### ISSUE THREAD

**Issue by Physium** [que-rb/que#360]
I struggling to figure out whats the best way to remove que from the project. 

Understand that we can leverage migration configs to set Que migration version back to 0 via `Que.migrate! version: 0`. However, this seems to cause issues after I remove the gem offically from the project as they the migration file has troubles understanding what `Que` is. Am I suppose to be deleting all Que related migration configs after setting migration version back to 0?

Currently on `Que version 0.14.3`

**Comment by ZimbiX** [comment]
Ah right, yeah, this is a symptom of having dependencies in migration files!

Hmm, you could define a `Que` null class with a `migrate!` method? e.g.:

```ruby
class Que
  def migrate!(**); end
end
```

**Comment by Physium** [comment]
> Ah right, yeah, this is a symptom of having dependencies in migration files!
> 
> Hmm, you could define a `Que` null class with a `migrate!` method? e.g.:
> 
> ```ruby
> class Que
>   def self.migrate!(**); end
> end
> ```
> 
> Edit: Out of curiosity, what are you moving to instead?

Thanks for the response! After reading about migrations, we are also considering purging off que migrations files as well.

My team was initially contemplating between using this or delayed job and we went with delayed job instead partly due to experience. Nothing against Que whatsoever, just that given our scenario we were under huge pressure to deliver fast. Delayed job has been working well for us and we are doing a series of cleaning up to purge off inactive or incompatible gems.

**Comment by ZimbiX** [comment]
Alrighty, I'm going to close this now =) Although we should probably document this
