### ISSUE TITLE
Timeline for v2.0.0. release

### ISSUE THREAD

**Issue by adamniedzielski** [que-rb/que#371]
Hello 👋 v2.0.0.beta1 has been around for a while. We would like to upgrade so we can move to Ruby 3, but the "beta" part scares us away. Is there still something that needs to be done before the v2.0.0. release?

**Comment by ZimbiX** [comment]
From Discord:

> whaleman — 30/07/2022
> Is there any sort of timeline or roadmap for when Que 2.0 will be out of beta?
> 
> ZimbiX — 30/07/2022
> Not exactly. Roughly, it'll be when we're confident about it. We are running it in production at GreenSync in some apps, and are in the process of upgrading the rest of our applications to it. There's the alternate upgrade process proposed by David that we still need to consider as well. But I do consider it stable enough, and I'd encourage people to try it already.
> 
> whaleman — 30/07/2022
> ah I see, thanks! We're trying to upgrade to ruby 3 before 2.7 is EOL (still 8 months to go) but the beta word always gives pause.
> 
> ZimbiX — 30/07/2022
> For sure. We're keen to avoid EOL too
