### ISSUE TITLE
Deprecated method used in connection.rb

### ISSUE THREAD

**Issue by drush** [que-rb/que#373]
https://github.com/que-rb/que/blob/f32cc7c6fc83c96a81c08a032c2bff758ee86f25/lib/que/connection.rb#L65

Error when running async tests:

```
/que-2.0.0.beta1/lib/que/connection.rb:65: warning: forwarding async_exec to async_exec_params and send_query to send_query_params is deprecated
```

[Rails issue 33185](https://github.com/rails/rails/issues/33185) on the same topic.

**Comment by ZimbiX** [comment]
Hah, I actually just noticed this last night myself!
