### ISSUE TITLE
upgrading from v0 to v2 when already on ruby 3

### ISSUE THREAD

**Issue by llimllib** [que-rb/que#385]
We have an app that is already on ruby 3, and has been running happily with Que 0.x for a long time (we're currently on the last 14.3 release).

I went in today to look at upgrading que, and unfortunately the migration instructions tell you that you must go through que version 1.x, which will not install if you're using ruby 3.

Is there any way to migrate from v0 to v2 when you're already running on ruby 3?

**Comment by adam12** [comment]
Que 1.4.0 doesn't have the Ruby version constraint in the gemspec. I haven't tried it but maybe upgrade to 1.4.0 first

**Comment by ZimbiX** [comment]
I was surprised to hear Que 0.x runs ok on Ruby 3! Did you get anywhere with this? I don't know much about Que 0.x and would be interested to hear about your upgrade journey. @owst is also on the path to upgrade from Que 0.x (mentioned in https://github.com/que-rb/que/issues/427)

The Que 1.x step is only necessary if zero downtime is important to you. If it's possible to clear the jobs table, I'd think you'd be able to skip past Que 1.x and apply all the migrations using Que 2.

Alternatively, you could try using Que 1.4.0 as suggested by @adam12. According to the [1.x branch](https://github.com/que-rb/que/compare/master...1.x), the only change in 1.4.1 was adding the Ruby version constraint. It should at least be able to run, given Que 1.4.0 effectively incorporates these changes: https://github.com/que-rb/que/pull/314.

**Comment by llimllib** [comment]
I'm pretty sure I gave up on this, but it was at my previous employer and quite a long time ago, so I don't exactly remember!

Feel free to close this if you like, I no longer am able to help figure it out

**Comment by ZimbiX** [comment]
Ah, that's a shame! Sorry it took me so long to get back to you.

Yeah, I will close this, but if you know anyone there who might've worked on this since, I'd still be keen to hear about how it went / is going.

**Comment by llimllib** [comment]
I totally understand, we had a great experience using que; thanks for all the work you put in
