### ISSUE TITLE
Migration fails when adding Que to a new project (with rspec)

### ISSUE THREAD

**Issue by FedeDeMartino** [que-rb/que#397]
I have a new project where I want to add Que gem.

I added the gem with the migration from the documentation
```ruby
class CreateQueSchema < ActiveRecord::Migration[7.0]
  def up
    Que.migrate!(version: 7)
  end

  def down
    Que.migrate!(version: 0)
  end
end
```

Which created the following table in my schema
```ruby
create_table "que_jobs", comment: "7", force: :cascade do |t|
    t.integer "priority", limit: 2, default: 100, null: false
    t.timestamptz "run_at", default: -> { "now()" }, null: false
    t.text "job_class", null: false
    t.integer "error_count", default: 0, null: false
    t.text "last_error_message"
    t.text "queue", default: "default", null: false
    t.text "last_error_backtrace"
    t.timestamptz "finished_at"
    t.timestamptz "expired_at"
    t.jsonb "args", default: [], null: false
    t.jsonb "data", default: {}, null: false
    t.integer "job_schema_version", null: false
    t.jsonb "kwargs", default: {}, null: false
    t.index ["args"], name: "que_jobs_args_gin_idx", opclass: :jsonb_path_ops, using: :gin
    t.index ["data"], name: "que_jobs_data_gin_idx", opclass: :jsonb_path_ops, using: :gin
    t.index ["job_schema_version", "queue", "priority", "run_at", "id"], name: "que_poll_idx", where: "((finished_at IS NULL) AND (expired_at IS NULL))"
    t.index ["kwargs"], name: "que_jobs_kwargs_gin_idx", opclass: :jsonb_path_ops, using: :gin
    t.check_constraint "char_length(\nCASE job_class\n    WHEN 'ActiveJob::QueueAdapters::QueAdapter::JobWrapper'::text THEN (args -> 0) ->> 'job_class'::text\n    ELSE job_class\nEND) <= 200", name: "job_class_length"
    t.check_constraint "char_length(last_error_message) <= 500 AND char_length(last_error_backtrace) <= 10000", name: "error_length"
    t.check_constraint "char_length(queue) <= 100", name: "queue_length"
    t.check_constraint "jsonb_typeof(args) = 'array'::text", name: "valid_args"
    t.check_constraint "jsonb_typeof(data) = 'object'::text AND (NOT data ? 'tags'::text OR jsonb_typeof(data -> 'tags'::text) = 'array'::text AND jsonb_array_length(data -> 'tags'::text) <= 5 AND que_validate_tags(data -> 'tags'::text))", name: "valid_data"
  end

  create_table "que_lockers", primary_key: "pid", id: :integer, default: nil, force: :cascade do |t|
    t.integer "worker_count", null: false
    t.integer "worker_priorities", null: false, array: true
    t.integer "ruby_pid", null: false
    t.text "ruby_hostname", null: false
    t.text "queues", null: false, array: true
    t.boolean "listening", null: false
    t.integer "job_schema_version", default: 1
    t.check_constraint "array_ndims(queues) = 1 AND array_length(queues, 1) IS NOT NULL", name: "valid_queues"
    t.check_constraint "array_ndims(worker_priorities) = 1 AND array_length(worker_priorities, 1) IS NOT NULL", name: "valid_worker_priorities"
  end

  create_table "que_values", primary_key: "key", id: :text, force: :cascade do |t|
    t.jsonb "value", default: {}, null: false
    t.check_constraint "jsonb_typeof(value) = 'object'::text", name: "valid_value"
  end
```

when I migrate and use que normally in my application everything seems to work fine. However, when I run the specs with rspec I get the following error
<img width="436" alt="image" src="https://github.com/que-rb/que/assets/115242837/719fb246-1408-40e6-8493-a476db9d2a65">

After a lot of time of trying to debug I discovered that If I comment out the following line `t.check_constraint "jsonb_typeof(data) = 'object'::text AND (NOT data ? 'tags'::text OR jsonb_typeof(data -> 'tags'::text) = 'array'::text AND jsonb_array_length(data -> 'tags'::text) <= 5 AND que_validate_tags(data -> 'tags'::text))", name: "valid_data"` in the `que_jobs` table everything seems to be working fine

<img width="1084" alt="image" src="https://github.com/que-rb/que/assets/115242837/5fddfedc-9f44-41ce-923a-4f14f9269f20">

**Comment by FedeDeMartino** [comment]
I'm using the latest que version `que (2.2.1)`

**Comment by oeoeaio** [comment]
Hey @FedeDeMartino, sorry to hear that you encountered this. Which version of postgres are you using, out of interest?

**Comment by FedeDeMartino** [comment]
> Hey @FedeDeMartino, sorry to hear that you encountered this. Which version of postgres are you using, out of interest?

I'm using version 14.7 :)

**Comment by mokolabs** [comment]
This is also happening to me. Rails 7. Que 2.2.1. Postgres 14.5.

I was really hoping to use Que in my app, but I can't until this migration works properly.

**Comment by ZimbiX** [comment]
@FedeDeMartino @mokolabs I'm having trouble reproducing this. Would either of you please be able to provide reproduction steps/repo? Is there definitely no other relevant error information shown?

I suspect this is a bug in a particular version(s) of Rails 7. I am assuming it'd be present in Rails 7.0.6, as that was the [latest available version at the time of the last comment, Aug 8](https://rubygems.org/gems/rails/versions).

Here's what I tried:

-   ```bash
    docker run -e POSTGRES_PASSWORD=que -e POSTGRES_USER=que -e POSTGRES_DB=que -p 5432:5432 -d postgres:14.7
    gem install rails -v 7.0.6
    rails _7.0.6_ new rails-app-with-que --database=postgresql
    cd rails-app-with-que
    bundle add que -v 2.2.1
    ```
- Update `Gemfile` to say: `gem "rails", "7.0.6"`
- Add to `default` database in `config/database.yml`:

    ```yaml
    host: localhost
    username: que
    password: que
    ```
-   ```bash
    bundle
    bundle exec rails generate migration create_que_schema
    ```
-  Add migration content as above
-   ```bash
    bundle exec rails db:create
    bundle exec rails db:migrate
    bundle exec rails db:migrate RAILS_ENV=test
    ```
    This completes successfully

I also tried stepping the resulting app down through Rails patch versions. Migrating the test db still worked fine other than on Rails 7.0.0, where it has a strange (unrelated?) error:

```
/home/brendan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.0/lib/rails/railtie.rb:246:in `initialize': Rails::Engine is abstract, you cannot instantiate it directly. (RuntimeError)
	from /home/brendan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.0/lib/rails/railtie.rb:184:in `new'
	from /home/brendan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.0/lib/rails/railtie.rb:184:in `instance'
	from /home/brendan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.0/lib/rails/railtie.rb:223:in `method_missing'
	from /home/brendan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.0/lib/active_support/descendants_tracker.rb:90:in `descendants'
	from /home/brendan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.0/lib/active_support/callbacks.rb:923:in `block in define_callbacks'
	from /home/brendan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.0/lib/active_support/callbacks.rb:920:in `each'
	from /home/brendan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.0/lib/active_support/callbacks.rb:920:in `define_callbacks'
	from /home/brendan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.0/lib/rails/engine.rb:427:in `<class:Engine>'
	from /home/brendan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.0/lib/rails/engine.rb:349:in `<module:Rails>'
	from /home/brendan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.0/lib/rails/engine.rb:11:in `<main>'
	from <internal:/home/brendan/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/home/brendan/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /home/brendan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /home/brendan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.0/lib/rails/application.rb:11:in `<main>'
	from <internal:/home/brendan/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/home/brendan/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /home/brendan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /home/brendan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.0/lib/rails.rb:13:in `<main>'
	from <internal:/home/brendan/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/home/brendan/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /home/brendan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /home/brendan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.0/lib/rails/all.rb:5:in `<main>'
	from <internal:/home/brendan/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/home/brendan/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /home/brendan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /home/brendan/Projects/que/rails-app-with-que/config/application.rb:3:in `<main>'
	from <internal:/home/brendan/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/home/brendan/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /home/brendan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /home/brendan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.0/lib/rails/command/actions.rb:22:in `require_application!'
	from /home/brendan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.0/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
	from /home/brendan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.0/lib/rails/commands/generate/generate_command.rb:21:in `perform'
	from /home/brendan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	from /home/brendan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/brendan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
	from /home/brendan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.0/lib/rails/command/base.rb:87:in `perform'
	from /home/brendan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.0/lib/rails/command.rb:48:in `invoke'
	from /home/brendan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.0/lib/rails/commands.rb:18:in `<main>'
	from <internal:/home/brendan/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/home/brendan/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /home/brendan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from bin/rails:4:in `<main>'
```

Sadly, `rails _7.0.0_ new` actually installs and uses 7.0.8, so it's not easy to generate a Rails app of a previous patch version =\

**Comment by enjaku4** [comment]
@ZimbiX I'm not convinced the problem was caused by running `rails db:migrate` in the first place, and I don't think it has something to do with Rails. The migrations run smoothly. But I came across similar issue today while setting up my test environment. Specifically, the problem occurred when I was setting up the database using `rails db:schema:load` or `rails db:prepare`. This happens because these commands load the database schema from the `schema.rb` file, which references the `que_validate_tags` function:

<img width="983" alt="Screenshot 2024-04-12 at 19 49 17" src="https://github.com/que-rb/que/assets/32835381/70aabab6-edb8-4bad-a118-9ca685dddeb2">

The database knows nothing about that function, hence the error. And that's why there is no error if that line in the `schema.rb` file is commented out as @FedeDeMartino noted.

I solved this problem by setting `config.active_record.schema_format = :sql`, which forces the application to use `structure.sql` instead of `schema.rb`. The `structure.sql` file explicitly defines `que_validate_tags`, so the structure can be loaded into the database without any problems.

**Comment by ZimbiX** [comment]
Ah ha. I'm glad you figured this out. Using `schema.rb` is not supported - [see the first paragraph of the 'Additional Rails-specific Setup' section in the readme](https://github.com/que-rb/que#additional-rails-specific-setup). I apologise for not noticing that's what you were using.

Perhaps we should check for use of `schema.rb` and raise a friendlier error.

**Comment by ZimbiX** [comment]
It turns out there's already an issue for this: https://github.com/que-rb/que/issues/103

**Comment by o-200** [comment]
Main issue that ActiveRecord::Migration clearing functions while executing `rails db:migrate`. So we're got problem that after `rails db:migrate` in database is no needed `que_validate_tags` function.

switching to structure.sql is really can solve this problem, but also im will recommend is to try [arfi](https://github.com/unurgunite/arfi)

`The ARFI gem provides the ability to create and maintain custom SQL functions for ActiveRecord models without switching to structure.sql (an SQL-based schema). You can use your own SQL functions in any part of the project, from migrations and models to everything else.`

im not tried it, but it can solve this problem if we create [que_validate_tags function](https://github.com/que-rb/que/blob/master/lib/que/migrations/4/up.sql) and execute all migrations separately.

At this week im will try it and update my comment with my results
