### ISSUE TITLE
All symbols, passed to the Job.run are transformed to strings

### ISSUE THREAD

**Issue by k1r8r0wn** [que-rb/que#416]
In given example:

```ruby
class TestJob <  Que::Job
  def run(action)
     TestInteractor.call!(action:)
  end
end

TestJob.enqueue(:symbol)
```

Inside **run** method **action.class** gives **String** instead of passed **Symbol** into the job.

P.S. Even if the hash is passed, all args inside have been changed to String. Is it okay & why so?

**Comment by ZimbiX** [comment]
From the readme: :wink:

> Also note that any arguments you pass will be serialized to JSON and back again, so stick to simple types (strings, integers, floats, hashes, and arrays).

**Comment by k1r8r0wn** [comment]
Appreciated that, @ZimbiX, missed that.

Have a good one!
